version: "3"

services:
  docker-web-gui:
    container_name: docker-web-gui
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - BIND_HOST=0.0.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always  # This ensures the container auto-starts and restarts on failure
