version: "3"

services:
  docker-web-gui:
    container_name: docker-web-gui
    build:
      context: .
    ports:
      - "3230:3230"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
